# NumPy Arrays

In [1]:
mylist = [1,2,3]

In [1]:
import numpy as np

In [3]:
array = np.array(mylist)

In [4]:
array

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr = np.arange(25)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
ranarr = np.random.randint(0,50,10)

In [16]:
ranarr

array([28, 11, 18, 36, 40, 17, 31, 17, 16, 14])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.max()

40

In [19]:
ranarr

array([28, 11, 18, 36, 40, 17, 31, 17, 16, 14])

In [20]:
ranarr.argmax()

4

In [21]:
ranarr.argmin()

1

In [22]:
arr = arr.reshape(5,5)

In [23]:
arr.shape

(5, 5)

In [24]:
arr.dtype

dtype('int32')

# Numpy Indexing and Selection

In [25]:
import numpy as np

In [26]:
arr = np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[8]

8

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [31]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [32]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr[0:5] = 100

In [34]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
slice_of_arr = arr[0:6]

In [38]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [39]:
slice_of_arr[:] = 99

In [40]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arr_copy = arr.copy()

In [44]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# NumPy Indexing and Selection


In [46]:
import numpy as np

In [48]:
arr_2nd = np.array([[5,10,15],[20,25,30],[35,40,35]])

In [49]:
arr_2nd

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 35]])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
bool_arr = arr > 5

In [67]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [70]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [71]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [73]:
arr[arr<3]

array([1, 2])

In [75]:
arr_2d = np.arange(50).reshape(5,10)

In [77]:
arr_2d[1:3, 3:5]


array([[13, 14],
       [23, 24]])

# NumPy Operations
  * Array with Array
  * Array with Scalars
  * Universal Array Functions

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [12]:
arr/arr

C:\Users\lengu\AppData\Local\Temp/ipykernel_16564/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1 / arr

C:\Users\lengu\AppData\Local\Temp/ipykernel_16564/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.max(arr)

10

In [18]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [19]:
np.log(arr)

C:\Users\lengu\AppData\Local\Temp/ipykernel_16564/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])